Bump io.github.hakky54:logcaptor from 2.12.1 to 2.12.2 (#44)
* Bump io.github.hakky54:logcaptor from 2.12.1 to 2.12.2

Bumps [io.github.hakky54:logcaptor](https://github.com/Hakky54/log-captor) from 2.12.1 to 2.12.2.
- [Changelog](https://github.com/Hakky54/log-captor/blob/master/CHANGELOG.MD)
- [Commits](https://github.com/Hakky54/log-captor/compare/v2.12.1...v2.12.2)

---
updated-dependencies:
- dependency-name: io.github.hakky54:logcaptor
  dependency-version: 2.12.2
  dependency-type: direct:development
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* fix for sonar token

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Dominique Boeckli <dboeckli@gmail.com>

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -351,6 +351,15 @@ jobs:
           set -o nounset     # abort on unbound variable
           set -o errexit     # abort on nonzero exit status
           
+          # Check if required parameters are set
+          required_params=("SONAR_TOKEN" "ORGANIZATION")
+          for param in "${required_params[@]}"; do
+            if [ -z "${!param}" ]; then
+              echo "::error::Required parameter $param is not set"
+              exit 1
+            fi
+          done
+          
           if [[ "${BRANCH_NAME}" == "master" ||  "${BRANCH_NAME}" == "main" ]]; then
             mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                   -s $GITHUB_WORKSPACE/settings.xml \
